// src/handlers/component-radar.js
// Component radar: scan PUBLIC sources, discover improvements, generate proposals
// CRITICAL RESTRICTIONS (enforced in code):
// - MAY: read public sources (with timeout), read local component state
// - MUST NOT: install packages, change code, change prompts, alter permissions/capsules, deploy, schedule itself, self-promote

const BLOCKED_ACTIONS = Object.freeze([
  'package.install',
  'code.modify',
  'prompt.change',
  'permission.alter',
  'capsule.alter',
  'deployment.trigger',
  'schedule.self',
  'proposal.self_promote_past_gate',
]);

// Timeout for public source reads (bounded to prevent resource exhaustion)
const PUBLIC_SOURCE_READ_TIMEOUT_MS = 30000;

// Validate that a handler name is NOT in the blocked list
function validateBlockedActionNotAttempted(actionType) {
  if (BLOCKED_ACTIONS.includes(actionType)) {
    throw new Error(`[SECURITY] component-radar BLOCKED: ${actionType}. Radar can only read and propose, never modify.`);
  }
}

const handlers = {
  'radar.scan-releases': async function({ input, state, signal }) {
    // Read public release feeds (with timeout)
    // Input: source (e.g., 'github', 'npm'), component type, scan depth
    // This is a pure read-only operation; no modification attempted
    if (!input.source || !input.componentType) {
      throw new Error('scan-releases requires source and componentType');
    }

    const sources = {
      github: 'https://github.com/<org>/<repo>/releases',
      npm: 'https://registry.npmjs.org/<package>',
      changelog: 'https://<component>/CHANGELOG.md',
    };

    // Simulate bounded timeout
    let timedOut = false;
    const timeoutHandle = setTimeout(() => {
      timedOut = true;
    }, PUBLIC_SOURCE_READ_TIMEOUT_MS);

    try {
      // In production: fetch from actual APIs with real timeout
      // For Phase 6: return mock scan results
      if (timedOut) {
        throw new Error(`scan-releases timed out after ${PUBLIC_SOURCE_READ_TIMEOUT_MS}ms`);
      }

      return {
        scanned: true,
        source: input.source,
        componentType: input.componentType,
        scanDepth: input.scanDepth || 'shallow',
        releases: [
          {
            version: '1.2.0',
            timestamp: new Date().toISOString(),
            notes: 'security fix for X, performance improvement for Y'
          }
        ],
        timestamp: new Date().toISOString()
      };
    } finally {
      clearTimeout(timeoutHandle);
    }
  },

  'radar.read-local-component-state': async function({ input, state, signal }) {
    // Read ONLY local component inventory and state
    // This is a read-only operation; no modifications
    if (!input.componentId) {
      throw new Error('read-local-component-state requires componentId');
    }

    // No validation needed here - this is a pure read operation
    return {
      componentId: input.componentId,
      state: 'healthy', // or 'degraded', 'failed'
      version: '1.0.0',
      lastChecked: new Date().toISOString(),
      canUpdate: true,
      updateAvailable: '1.1.0'
    };
  },

  'radar.generate-proposal': async function({ input, state, signal }) {
    // Generate a proposal based on scan results
    // CRITICAL: this handler ONLY GENERATES THE PROPOSAL OBJECT
    // It does NOT stage the proposal, does NOT promote itself past a gate, does NOT modify state
    // This is a pure data generation operation, no modifications attempted
    if (!input.problem || !input.evidence) {
      throw new Error('generate-proposal requires problem and evidence');
    }

    // Build a complete proposal with all 9 required fields
    const proposal = {
      problem: input.problem,
      evidence: input.evidence,
      alternatives: input.alternatives || [
        'do nothing and wait for manual upgrade',
        'pin to current version indefinitely'
      ],
      compatibility: input.compatibility || 'check release notes for breaking changes',
      security: input.security || 'review security advisories',
      cost: input.cost || 'minimal - dependency update only',
      test_plan: input.testPlan || 'run existing test suite, monitor for regressions',
      rollback_procedure: input.rollbackProcedure || 'revert dependency version in package.json and restart',
      expected_benefit: input.expectedBenefit || 'performance improvement, security fixes'
    };

    // GUARD: do NOT attempt to promote this proposal past any gate
    // Just return the proposal object as data
    return {
      proposalGenerated: true,
      proposal,
      nextAction: 'stage_proposal_for_human_review',
      warningNote: 'Proposal generated by radar. Human must stage and promote through approval gates.'
    };
  },

  'radar.validate-proposal-safety': async function({ input, state, signal }) {
    // Validate that a proposed change is safe (read-only check, no modifications)
    // This is a pure validation/analysis operation, no modifications attempted
    if (!input.changeType || !input.changeTarget) {
      throw new Error('validate-proposal-safety requires changeType and changeTarget');
    }

    // Check that the change is a known-safe type
    const safeTypes = [
      'dependency-update',
      'version-bump',
      'config-addition',
      'documentation-update'
    ];

    if (!safeTypes.includes(input.changeType)) {
      return {
        safe: false,
        reason: `change type ${input.changeType} is not in the safe-types list`
      };
    }

    // Check that the change target is not a critical system component
    const criticalTargets = [
      'signer-key',
      'auth-handler',
      'state-machine-core',
      'permission-model'
    ];

    if (criticalTargets.some(t => input.changeTarget.includes(t))) {
      return {
        safe: false,
        reason: `change target ${input.changeTarget} touches a critical component`
      };
    }

    return {
      safe: true,
      changeType: input.changeType,
      changeTarget: input.changeTarget,
      estimatedRisk: 'low',
      timestamp: new Date().toISOString()
    };
  },

  'radar.report-scan': async function({ input, state, signal }) {
    // Generate a scan report (data only, no state changes)
    // Output: structured report of findings, ready for human review
    return {
      reportGenerated: true,
      scanId: `scan_${Math.random().toString(36).slice(2, 9)}`,
      timestamp: new Date().toISOString(),
      componentsScanned: input.componentsScanned || 0,
      proposalsGenerated: input.proposalsGenerated || 0,
      riskAssessment: input.riskAssessment || 'all proposals reviewed and deemed safe for canary'
    };
  }
};

module.exports = {
  handlers,
  BLOCKED_ACTIONS,
  PUBLIC_SOURCE_READ_TIMEOUT_MS,
  validateBlockedActionNotAttempted,
};
